spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        query:
          limit:
            inspection_strategy: legacy

logging:
  level:
    org.hibernate.SQL: debug
server:
  error:
    whitelabel:
      enabled: false